import "dotenv/config";

import {
  DEMO_CATEGORY_IMAGES,
  DEMO_DIAMOND_IMAGES,
  DEMO_RING_IMAGES,
  DEMO_SETTING_IMAGES,
  demoImage,
} from "@/constants/demo-images";
import { connectDB } from "@/lib/db";
import { hashPassword } from "@/lib/password";
import { generateOrderNumber } from "@/lib/utils";
import { Appointment } from "@/models/Appointment";
import { Category } from "@/models/Category";
import { Diamond } from "@/models/Diamond";
import { Order } from "@/models/Order";
import { Product } from "@/models/Product";
import { RingSetting } from "@/models/RingSetting";
import { User } from "@/models/User";

async function seed() {
  console.log("Connecting to MongoDB...");
  await connectDB();

  console.log("Clearing existing data...");
  await Promise.all([
    User.deleteMany({}),
    Category.deleteMany({}),
    Product.deleteMany({}),
    Diamond.deleteMany({}),
    RingSetting.deleteMany({}),
    Order.deleteMany({}),
    Appointment.deleteMany({}),
  ]);

  console.log("Creating admin user...");
  await User.create({
    name: "Admin User",
    email: "admin@didi.com",
    passwordHash: await hashPassword("admin123"),
    role: "super_admin",
    isActive: true,
  });

  console.log("Creating categories...");
  await Category.insertMany([
    {
      name: "Loose Diamonds",
      slug: "loose-diamonds",
      description: "Certified loose diamonds, selected one at a time.",
      image: DEMO_CATEGORY_IMAGES.looseDiamonds,
      isActive: true,
    },
    {
      name: "Engagement Rings",
      slug: "engagement-rings",
      description: "Diamond engagement rings and solitaire styles.",
      image: DEMO_CATEGORY_IMAGES.engagementRings,
      isActive: true,
    },
    {
      name: "Diamond Rings",
      slug: "diamond-rings",
      description: "Refined diamond ring styles for meaningful moments.",
      image: DEMO_CATEGORY_IMAGES.diamondRings,
      isActive: true,
    },
    {
      name: "Signature Solitaires",
      slug: "signature-solitaires",
      description: "Quiet, timeless solitaire diamond rings.",
      image: DEMO_CATEGORY_IMAGES.signatureSolitaires,
      isActive: true,
    },
    {
      name: "Oval Cut Diamonds",
      slug: "oval-cut-diamonds",
      description: "Elegant oval diamonds with soft, elongated brilliance.",
      image: DEMO_CATEGORY_IMAGES.ovalCut,
      isActive: true,
    },
    {
      name: "Round Brilliant Diamonds",
      slug: "round-brilliant-diamonds",
      description: "Classic round brilliant diamonds with exceptional fire.",
      image: DEMO_CATEGORY_IMAGES.roundBrilliant,
      isActive: true,
    },
    {
      name: "Emerald Cut Diamonds",
      slug: "emerald-cut-diamonds",
      description: "Architectural emerald cut diamonds with quiet sophistication.",
      image: DEMO_CATEGORY_IMAGES.emeraldCut,
      isActive: true,
    },
    {
      name: "Custom Ring Settings",
      slug: "custom-ring-settings",
      description: "Settings for the ring builder — separate from your diamond.",
      image: DEMO_CATEGORY_IMAGES.ringSettings,
      isActive: true,
    },
    {
      name: "Necklaces",
      slug: "necklaces",
      description: "Lab-grown diamond necklaces from Asteria Diamond House.",
      image: DEMO_RING_IMAGES.pearFiligree,
      isActive: true,
    },
    {
      name: "Earrings",
      slug: "earrings",
      description: "Lab-grown diamond earrings crafted in Thessaloniki.",
      image: DEMO_DIAMOND_IMAGES.roundBrilliant,
      isActive: true,
    },
    {
      name: "Bracelets",
      slug: "bracelets",
      description: "Lab-grown diamond bracelets and tennis styles.",
      image: DEMO_RING_IMAGES.hiddenHalo,
      isActive: true,
    },
    {
      name: "Colored Lab-Grown Diamonds",
      slug: "colored-lab-grown-diamonds",
      description: "Blue, yellow, and pink lab-grown diamond jewelry.",
      image: DEMO_DIAMOND_IMAGES.cushion,
      isActive: true,
    },
  ]);

  const categories = await Category.find();
  const engagementCategory = categories.find((c) => c.slug === "engagement-rings")!;
  const solitaireCategory = categories.find((c) => c.slug === "signature-solitaires")!;
  const diamondRingsCategory = categories.find((c) => c.slug === "diamond-rings")!;
  const necklacesCategory = categories.find((c) => c.slug === "necklaces")!;
  const earringsCategory = categories.find((c) => c.slug === "earrings")!;
  const braceletsCategory = categories.find((c) => c.slug === "bracelets")!;
  const coloredCategory = categories.find(
    (c) => c.slug === "colored-lab-grown-diamonds",
  )!;

  console.log("Creating products...");
  await Product.insertMany([
    {
      name: "Oval Solitaire Diamond Ring",
      slug: "oval-solitaire-diamond-ring",
      sku: "DR-001",
      productType: "engagement-ring",
      categoryId: engagementCategory._id,
      shortDescription: "An oval diamond in a refined four-prong solitaire setting.",
      description:
        "A quietly elegant oval solitaire, crafted to let your diamond speak for itself. Available in platinum and 18k gold.",
      basePrice: 1450,
      salePrice: 1299,
      images: [
        demoImage(DEMO_RING_IMAGES.ovalSolitaire, "Oval Solitaire Diamond Ring"),
      ],
      variants: [
        {
          sku: "DR-001-WG",
          metal: "white-gold",
          price: 1450,
          salePrice: 1299,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.ovalSolitaire,
        },
        {
          sku: "DR-001-YG",
          metal: "yellow-gold",
          price: 1420,
          salePrice: 1275,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.ovalSolitaire,
        },
        {
          sku: "DR-001-PT",
          metal: "platinum",
          price: 1680,
          salePrice: 1495,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.ovalSolitaire,
        },
      ],
      attributes: {
        metal: ["white-gold", "yellow-gold", "platinum"],
        stoneType: "diamond",
        diamondShape: "oval",
        style: "solitaire",
        ringSizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8"],
      },
      stockQuantity: 6,
      availabilityStatus: "made-to-order",
      productionTime: "2–3 weeks",
      isFeatured: true,
      isBestSeller: true,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Round Brilliant Diamond Ring",
      slug: "round-brilliant-diamond-ring",
      sku: "DR-002",
      productType: "engagement-ring",
      categoryId: solitaireCategory._id,
      shortDescription: "A classic round brilliant in a signature solitaire setting.",
      description:
        "Timeless round brilliant proportions paired with a clean, low-profile solitaire band — understated and enduring.",
      basePrice: 1380,
      images: [
        demoImage(DEMO_RING_IMAGES.roundSolitaire, "Round Brilliant Diamond Ring"),
      ],
      variants: [
        {
          sku: "DR-002-WG",
          metal: "white-gold",
          price: 1380,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.roundSolitaire,
        },
        {
          sku: "DR-002-PT",
          metal: "platinum",
          price: 1580,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.roundSolitaire,
        },
      ],
      attributes: {
        metal: ["white-gold", "platinum"],
        stoneType: "diamond",
        diamondShape: "round",
        style: "solitaire",
        ringSizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8"],
      },
      stockQuantity: 4,
      availabilityStatus: "made-to-order",
      productionTime: "2–3 weeks",
      isFeatured: true,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Emerald Cut Signature Ring",
      slug: "emerald-cut-signature-ring",
      sku: "DR-003",
      productType: "engagement-ring",
      categoryId: diamondRingsCategory._id,
      shortDescription: "An emerald cut diamond in a tailored signature setting.",
      description:
        "Architectural lines and a step-cut diamond create a composed, gallery-worthy ring with calm presence.",
      basePrice: 1680,
      images: [
        demoImage(DEMO_RING_IMAGES.emeraldCut, "Emerald Cut Signature Ring"),
      ],
      variants: [
        {
          sku: "DR-003-WG",
          metal: "white-gold",
          price: 1680,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.emeraldCut,
        },
        {
          sku: "DR-003-PT",
          metal: "platinum",
          price: 1880,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.emeraldCut,
        },
      ],
      attributes: {
        metal: ["white-gold", "platinum"],
        stoneType: "diamond",
        diamondShape: "emerald",
        style: "solitaire",
        ringSizes: ["5", "5.5", "6", "6.5", "7"],
      },
      stockQuantity: 3,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: true,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Hidden Halo Diamond Ring",
      slug: "hidden-halo-diamond-ring",
      sku: "DR-004",
      productType: "engagement-ring",
      categoryId: engagementCategory._id,
      shortDescription: "A concealed halo that adds brilliance without excess.",
      description:
        "A hidden halo beneath the centre diamond offers subtle radiance — refined, not ornate. Ideal for round and oval centres.",
      basePrice: 1920,
      images: [
        demoImage(DEMO_RING_IMAGES.hiddenHalo, "Hidden Halo Diamond Ring"),
      ],
      variants: [
        {
          sku: "DR-004-WG",
          metal: "white-gold",
          price: 1920,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.hiddenHalo,
        },
        {
          sku: "DR-004-RG",
          metal: "rose-gold",
          price: 1890,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.hiddenHalo,
        },
        {
          sku: "DR-004-PT",
          metal: "platinum",
          price: 2120,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.hiddenHalo,
        },
      ],
      attributes: {
        metal: ["white-gold", "rose-gold", "platinum"],
        stoneType: "diamond",
        diamondShape: "round",
        style: "halo",
        ringSizes: ["5", "5.5", "6", "6.5", "7"],
      },
      stockQuantity: 5,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: false,
      isBestSeller: true,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Cushion Split Shank Ring",
      slug: "cushion-split-shank-ring",
      sku: "DR-005",
      productType: "engagement-ring",
      categoryId: engagementCategory._id,
      shortDescription: "A cushion centre with a pavé split shank in two-tone gold.",
      description:
        "Soft cushion brilliance framed by a delicate split shank — warm yellow gold with white-metal accents.",
      basePrice: 2100,
      images: [
        demoImage(
          DEMO_RING_IMAGES.cushionSplitShank,
          "Cushion Split Shank Ring",
        ),
      ],
      variants: [
        {
          sku: "DR-005-YG",
          metal: "yellow-gold",
          price: 2100,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.cushionSplitShank,
        },
        {
          sku: "DR-005-RG",
          metal: "rose-gold",
          price: 2080,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.cushionSplitShank,
        },
      ],
      attributes: {
        metal: ["yellow-gold", "rose-gold"],
        stoneType: "diamond",
        diamondShape: "cushion",
        style: "pave",
        ringSizes: ["5", "5.5", "6", "6.5", "7", "7.5"],
      },
      stockQuantity: 3,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: true,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Princess Channel Diamond Ring",
      slug: "princess-channel-diamond-ring",
      sku: "DR-006",
      productType: "engagement-ring",
      categoryId: diamondRingsCategory._id,
      shortDescription: "A princess centre with channel-set side stones.",
      description:
        "Architectural sparkle — a square princess diamond with continuous channel-set companions in white metal.",
      basePrice: 2250,
      images: [
        demoImage(
          DEMO_RING_IMAGES.princessChannel,
          "Princess Channel Diamond Ring",
        ),
      ],
      variants: [
        {
          sku: "DR-006-WG",
          metal: "white-gold",
          price: 2250,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.princessChannel,
        },
        {
          sku: "DR-006-PT",
          metal: "platinum",
          price: 2480,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.princessChannel,
        },
      ],
      attributes: {
        metal: ["white-gold", "platinum"],
        stoneType: "diamond",
        diamondShape: "princess",
        style: "channel",
        ringSizes: ["5", "5.5", "6", "6.5", "7"],
      },
      stockQuantity: 3,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: false,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Pear Filigree Gold Ring",
      slug: "pear-filigree-gold-ring",
      sku: "DR-007",
      productType: "engagement-ring",
      categoryId: engagementCategory._id,
      shortDescription: "A pear diamond in a vintage-inspired filigree bezel.",
      description:
        "Romantic milgrain and openwork shoulders cradle a brilliant pear — quiet heritage, modern light.",
      basePrice: 1980,
      images: [
        demoImage(DEMO_RING_IMAGES.pearFiligree, "Pear Filigree Gold Ring"),
      ],
      variants: [
        {
          sku: "DR-007-YG",
          metal: "yellow-gold",
          price: 1980,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.pearFiligree,
        },
      ],
      attributes: {
        metal: ["yellow-gold"],
        stoneType: "diamond",
        diamondShape: "pear",
        style: "vintage",
        ringSizes: ["5", "5.5", "6", "6.5", "7", "7.5"],
      },
      stockQuantity: 2,
      availabilityStatus: "made-to-order",
      productionTime: "4–5 weeks",
      isFeatured: true,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Asscher Three-Stone Ring",
      slug: "asscher-three-stone-ring",
      sku: "DR-008",
      productType: "engagement-ring",
      categoryId: diamondRingsCategory._id,
      shortDescription: "An Asscher centre with baguette side stones.",
      description:
        "Geometric calm — an Asscher hall-of-mirrors centre flanked by tapered baguettes on a platinum band.",
      basePrice: 2350,
      images: [
        demoImage(
          DEMO_RING_IMAGES.asscherThreeStone,
          "Asscher Three-Stone Ring",
        ),
      ],
      variants: [
        {
          sku: "DR-008-PT",
          metal: "platinum",
          price: 2350,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.asscherThreeStone,
        },
        {
          sku: "DR-008-WG",
          metal: "white-gold",
          price: 2180,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.asscherThreeStone,
        },
      ],
      attributes: {
        metal: ["platinum", "white-gold"],
        stoneType: "diamond",
        diamondShape: "asscher",
        style: "three-stone",
        ringSizes: ["5", "5.5", "6", "6.5", "7"],
      },
      stockQuantity: 3,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: false,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Marquise Bezel Dual-Tone Ring",
      slug: "marquise-bezel-dual-tone-ring",
      sku: "DR-009",
      productType: "engagement-ring",
      categoryId: diamondRingsCategory._id,
      shortDescription: "An east-west marquise in a dual-tone bezel.",
      description:
        "Modern and architectural — a horizontal marquise set in white metal with a warm gold inner rim.",
      basePrice: 2050,
      images: [
        demoImage(
          DEMO_RING_IMAGES.marquiseBezel,
          "Marquise Bezel Dual-Tone Ring",
        ),
      ],
      variants: [
        {
          sku: "DR-009-WG",
          metal: "white-gold",
          price: 2050,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.marquiseBezel,
        },
        {
          sku: "DR-009-YG",
          metal: "yellow-gold",
          price: 2020,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.marquiseBezel,
        },
      ],
      attributes: {
        metal: ["white-gold", "yellow-gold"],
        stoneType: "diamond",
        diamondShape: "marquise",
        style: "bezel",
        ringSizes: ["5", "5.5", "6", "6.5", "7", "7.5"],
      },
      stockQuantity: 3,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: false,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Blue Lab-Grown Solitaire Ring",
      slug: "blue-lab-grown-solitaire-ring",
      sku: "CR-BLU-001",
      productType: "engagement-ring",
      categoryId: coloredCategory._id,
      shortDescription:
        "A serene blue lab-grown diamond in a refined solitaire setting.",
      description:
        "Blue lab-grown diamond jewelry from Asteria Diamond House in Thessaloniki — calm color with the clarity of a true diamond.",
      basePrice: 2480,
      images: [
        demoImage(DEMO_RING_IMAGES.roundSolitaire, "Blue Lab-Grown Solitaire Ring"),
      ],
      variants: [
        {
          sku: "CR-BLU-001-WG",
          metal: "white-gold",
          price: 2480,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.roundSolitaire,
        },
        {
          sku: "CR-BLU-001-PT",
          metal: "platinum",
          price: 2680,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.roundSolitaire,
        },
      ],
      attributes: {
        metal: ["white-gold", "platinum"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "round",
        diamondColor: "blue",
        diamondCarat: 1.02,
        style: "solitaire",
        ringSizes: ["5", "5.5", "6", "6.5", "7", "7.5"],
        customSizeAvailable: true,
        customStoneAvailable: true,
        shipsTo: "greece-eu",
        certification: {
          lab: "IGI",
          reportNumber: "LG12345001",
          reportUrl: "https://www.igi.org/",
        },
      },
      stockQuantity: 3,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: true,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Yellow Lab-Grown Oval Ring",
      slug: "yellow-lab-grown-oval-ring",
      sku: "CR-YEL-001",
      productType: "ring",
      categoryId: coloredCategory._id,
      shortDescription:
        "A warm yellow lab-grown diamond set in yellow gold.",
      description:
        "Yellow lab-grown diamond jewelry designed in Greece — radiant color for those who want something quietly distinctive.",
      basePrice: 2320,
      images: [
        demoImage(DEMO_RING_IMAGES.ovalSolitaire, "Yellow Lab-Grown Oval Ring"),
      ],
      variants: [
        {
          sku: "CR-YEL-001-YG",
          metal: "yellow-gold",
          price: 2320,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.ovalSolitaire,
        },
      ],
      attributes: {
        metal: ["yellow-gold"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "oval",
        diamondColor: "yellow",
        diamondCarat: 1.2,
        style: "solitaire",
        ringSizes: ["5", "6", "6.5", "7", "7.5"],
        customSizeAvailable: true,
        customStoneAvailable: true,
        shipsTo: "greece-eu",
        certification: {
          lab: "IGI",
          reportNumber: "LG12345002",
        },
      },
      stockQuantity: 2,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: true,
      isBestSeller: true,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Pink Lab-Grown Halo Ring",
      slug: "pink-lab-grown-halo-ring",
      sku: "CR-PNK-001",
      productType: "engagement-ring",
      categoryId: coloredCategory._id,
      shortDescription:
        "A soft pink lab-grown diamond framed by a delicate halo.",
      description:
        "Pink lab-grown diamond jewelry from Thessaloniki — gentle color, precise craft, and clear certification details.",
      basePrice: 2750,
      images: [
        demoImage(DEMO_RING_IMAGES.hiddenHalo, "Pink Lab-Grown Halo Ring"),
      ],
      variants: [
        {
          sku: "CR-PNK-001-RG",
          metal: "rose-gold",
          price: 2750,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.hiddenHalo,
        },
        {
          sku: "CR-PNK-001-WG",
          metal: "white-gold",
          price: 2780,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.hiddenHalo,
        },
      ],
      attributes: {
        metal: ["rose-gold", "white-gold"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "round",
        diamondColor: "pink",
        diamondCarat: 0.9,
        style: "halo",
        ringSizes: ["5", "5.5", "6", "6.5", "7"],
        customSizeAvailable: true,
        customStoneAvailable: true,
        shipsTo: "greece-eu",
        certification: {
          lab: "IGI",
          reportNumber: "LG12345003",
        },
      },
      stockQuantity: 2,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: true,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Lab-Grown Diamond Pendant Necklace",
      slug: "lab-grown-diamond-pendant-necklace",
      sku: "NK-001",
      productType: "necklace",
      categoryId: necklacesCategory._id,
      shortDescription:
        "A luminous lab-grown diamond pendant on a fine chain.",
      description:
        "Lab-grown diamond necklace from Asteria Diamond House — light at the collarbone, crafted in Greece.",
      basePrice: 980,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.roundBrilliant, "Lab-Grown Diamond Pendant Necklace"),
      ],
      variants: [
        {
          sku: "NK-001-WG",
          metal: "white-gold",
          price: 980,
          stockQuantity: 3,
          image: DEMO_DIAMOND_IMAGES.roundBrilliant,
        },
        {
          sku: "NK-001-YG",
          metal: "yellow-gold",
          price: 960,
          stockQuantity: 2,
          image: DEMO_DIAMOND_IMAGES.roundBrilliant,
        },
      ],
      attributes: {
        metal: ["white-gold", "yellow-gold"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "round",
        diamondColor: "colorless",
        diamondCarat: 0.5,
        customStoneAvailable: true,
        shipsTo: "greece-eu",
        certification: { lab: "IGI", reportNumber: "LG12345010" },
      },
      stockQuantity: 5,
      availabilityStatus: "in-stock",
      productionTime: "1–2 weeks",
      isFeatured: true,
      isBestSeller: true,
      isReadyToShip: true,
      status: "published",
    },
    {
      name: "Blue Lab-Grown Pear Pendant",
      slug: "blue-lab-grown-pear-pendant",
      sku: "NK-BLU-001",
      productType: "necklace",
      categoryId: coloredCategory._id,
      shortDescription: "A blue lab-grown pear diamond on a delicate chain.",
      description:
        "Colored lab-grown diamond necklace with a blue pear stone — designed in Thessaloniki for Greece and EU delivery.",
      basePrice: 1680,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.pear, "Blue Lab-Grown Pear Pendant"),
      ],
      variants: [
        {
          sku: "NK-BLU-001-WG",
          metal: "white-gold",
          price: 1680,
          stockQuantity: 2,
          image: DEMO_DIAMOND_IMAGES.pear,
        },
      ],
      attributes: {
        metal: ["white-gold"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "pear",
        diamondColor: "blue",
        diamondCarat: 0.75,
        customStoneAvailable: true,
        shipsTo: "greece-eu",
        certification: { lab: "IGI", reportNumber: "LG12345011" },
      },
      stockQuantity: 2,
      availabilityStatus: "made-to-order",
      productionTime: "2–3 weeks",
      isFeatured: true,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Lab-Grown Diamond Stud Earrings",
      slug: "lab-grown-diamond-stud-earrings",
      sku: "ER-001",
      productType: "earrings",
      categoryId: earringsCategory._id,
      shortDescription: "Classic lab-grown diamond studs for every day.",
      description:
        "Lab-grown diamond earrings from Asteria — quiet brilliance, clear specifications, made in Greece.",
      basePrice: 720,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.roundBrilliant, "Lab-Grown Diamond Stud Earrings"),
      ],
      variants: [
        {
          sku: "ER-001-WG",
          metal: "white-gold",
          price: 720,
          stockQuantity: 4,
          image: DEMO_DIAMOND_IMAGES.roundBrilliant,
        },
        {
          sku: "ER-001-PT",
          metal: "platinum",
          price: 820,
          stockQuantity: 2,
          image: DEMO_DIAMOND_IMAGES.roundBrilliant,
        },
      ],
      attributes: {
        metal: ["white-gold", "platinum"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "round",
        diamondColor: "colorless",
        diamondCarat: 0.4,
        customStoneAvailable: true,
        shipsTo: "greece-eu",
        certification: { lab: "IGI", reportNumber: "LG12345020" },
      },
      stockQuantity: 6,
      availabilityStatus: "in-stock",
      productionTime: "1–2 weeks",
      isFeatured: true,
      isBestSeller: true,
      isReadyToShip: true,
      status: "published",
    },
    {
      name: "Yellow Lab-Grown Drop Earrings",
      slug: "yellow-lab-grown-drop-earrings",
      sku: "ER-YEL-001",
      productType: "earrings",
      categoryId: coloredCategory._id,
      shortDescription: "Warm yellow lab-grown diamonds in a drop silhouette.",
      description:
        "Yellow lab-grown diamond earrings — color with clarity, from Asteria Diamond House in Thessaloniki.",
      basePrice: 1420,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.oval, "Yellow Lab-Grown Drop Earrings"),
      ],
      variants: [
        {
          sku: "ER-YEL-001-YG",
          metal: "yellow-gold",
          price: 1420,
          stockQuantity: 2,
          image: DEMO_DIAMOND_IMAGES.oval,
        },
      ],
      attributes: {
        metal: ["yellow-gold"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "oval",
        diamondColor: "yellow",
        diamondCarat: 0.6,
        customStoneAvailable: true,
        shipsTo: "greece-eu",
        certification: { lab: "IGI", reportNumber: "LG12345021" },
      },
      stockQuantity: 2,
      availabilityStatus: "made-to-order",
      productionTime: "2–3 weeks",
      isFeatured: false,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Lab-Grown Tennis Bracelet",
      slug: "lab-grown-tennis-bracelet",
      sku: "BR-001",
      productType: "bracelet",
      categoryId: braceletsCategory._id,
      shortDescription: "A continuous line of lab-grown diamonds.",
      description:
        "Lab-grown diamond bracelet from Asteria Diamond House — refined for Greece and EU delivery.",
      basePrice: 3200,
      images: [
        demoImage(DEMO_RING_IMAGES.hiddenHalo, "Lab-Grown Tennis Bracelet"),
      ],
      variants: [
        {
          sku: "BR-001-WG",
          metal: "white-gold",
          price: 3200,
          stockQuantity: 2,
          image: DEMO_RING_IMAGES.hiddenHalo,
        },
        {
          sku: "BR-001-YG",
          metal: "yellow-gold",
          price: 3150,
          stockQuantity: 1,
          image: DEMO_RING_IMAGES.hiddenHalo,
        },
      ],
      attributes: {
        metal: ["white-gold", "yellow-gold"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "round",
        diamondColor: "colorless",
        diamondCarat: 2.0,
        customSizeAvailable: true,
        customStoneAvailable: false,
        shipsTo: "greece-eu",
        certification: { lab: "IGI", reportNumber: "LG12345030" },
      },
      stockQuantity: 3,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: true,
      isBestSeller: true,
      isReadyToShip: false,
      status: "published",
    },
    {
      name: "Pink Lab-Grown Station Bracelet",
      slug: "pink-lab-grown-station-bracelet",
      sku: "BR-PNK-001",
      productType: "bracelet",
      categoryId: coloredCategory._id,
      shortDescription: "Pink lab-grown diamonds spaced along a fine bracelet.",
      description:
        "Pink lab-grown diamond bracelet — soft color, precise craft, from Thessaloniki.",
      basePrice: 2100,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.cushion, "Pink Lab-Grown Station Bracelet"),
      ],
      variants: [
        {
          sku: "BR-PNK-001-RG",
          metal: "rose-gold",
          price: 2100,
          stockQuantity: 1,
          image: DEMO_DIAMOND_IMAGES.cushion,
        },
      ],
      attributes: {
        metal: ["rose-gold"],
        goldPurity: "18k",
        stoneType: "lab-grown-diamond",
        isLabGrown: true,
        diamondShape: "cushion",
        diamondColor: "pink",
        diamondCarat: 1.1,
        customSizeAvailable: true,
        customStoneAvailable: true,
        shipsTo: "greece-eu",
        certification: { lab: "IGI", reportNumber: "LG12345031" },
      },
      stockQuantity: 1,
      availabilityStatus: "made-to-order",
      productionTime: "3–4 weeks",
      isFeatured: false,
      isBestSeller: false,
      isReadyToShip: false,
      status: "published",
    },
  ]);

  // Ensure classic ring seed pieces are marked as lab-grown for catalog consistency
  await Product.updateMany(
    { sku: { $regex: /^DR-/ } },
    {
      $set: {
        "attributes.isLabGrown": true,
        "attributes.stoneType": "lab-grown-diamond",
        "attributes.diamondColor": "colorless",
        "attributes.shipsTo": "greece-eu",
      },
    },
  );

  console.log("Creating diamonds...");
  await Diamond.insertMany([
    {
      diamondType: "natural",
      shape: "round",
      carat: 1.02,
      cut: "Ideal",
      color: "F",
      clarity: "VS1",
      polish: "Excellent",
      symmetry: "Excellent",
      fluorescence: "None",
      lengthMm: 6.45,
      widthMm: 6.48,
      depthMm: 3.95,
      tablePercent: 57,
      depthPercent: 61.2,
      lengthWidthRatio: 0.995,
      certification: {
        lab: "GIA",
        reportNumber: "2141234567",
        reportUrl: "https://www.gia.edu/report-check?reportno=2141234567",
      },
      collections: { flawless: false, blockchain: true, trulyBrilliant: true },
      price: 5200,
      images: [
        demoImage(
          DEMO_DIAMOND_IMAGES.roundBrilliant,
          "1.02 ct Round Brilliant Diamond",
        ),
      ],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "lab",
      shape: "oval",
      carat: 1.5,
      cut: "Super Ideal",
      color: "E",
      clarity: "VVS2",
      polish: "Excellent",
      symmetry: "Very Good",
      fluorescence: "Faint",
      lengthMm: 8.9,
      widthMm: 6.2,
      depthMm: 3.85,
      tablePercent: 58,
      depthPercent: 62.1,
      lengthWidthRatio: 1.435,
      certification: {
        lab: "IGI",
        reportNumber: "IGI-9876543210",
        reportUrl: "https://www.igi.org/reports",
      },
      collections: { flawless: false, blockchain: false, trulyBrilliant: true },
      price: 3800,
      salePrice: 3499,
      images: [demoImage(DEMO_DIAMOND_IMAGES.oval, "1.50 ct Oval Diamond")],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "natural",
      shape: "emerald",
      carat: 0.92,
      cut: "Very Good",
      color: "G",
      clarity: "VS2",
      polish: "Very Good",
      symmetry: "Very Good",
      fluorescence: "None",
      lengthMm: 6.4,
      widthMm: 4.7,
      depthMm: 3.15,
      tablePercent: 63,
      depthPercent: 67,
      lengthWidthRatio: 1.36,
      certification: {
        lab: "GIA",
        reportNumber: "5234567890",
      },
      collections: { flawless: false, blockchain: false, trulyBrilliant: false },
      price: 3400,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.emeraldCut, "0.92 ct Emerald Cut Diamond"),
      ],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "natural",
      shape: "princess",
      carat: 2.15,
      cut: "Super Ideal",
      color: "D",
      clarity: "FL",
      polish: "Excellent",
      symmetry: "Excellent",
      fluorescence: "None",
      lengthMm: 7.12,
      widthMm: 7.05,
      depthMm: 5.1,
      tablePercent: 68,
      depthPercent: 72,
      lengthWidthRatio: 1.01,
      certification: {
        lab: "GIA",
        reportNumber: "6482100999",
      },
      collections: { flawless: true, blockchain: true, trulyBrilliant: true },
      price: 18600,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.princess, "2.15 ct Princess Diamond"),
      ],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "natural",
      shape: "princess",
      carat: 2.04,
      cut: "Ideal",
      color: "E",
      clarity: "VVS1",
      polish: "Excellent",
      symmetry: "Excellent",
      fluorescence: "Medium",
      lengthMm: 6.95,
      widthMm: 6.88,
      depthMm: 4.95,
      tablePercent: 69,
      depthPercent: 71.5,
      lengthWidthRatio: 1.01,
      certification: {
        lab: "GIA",
        reportNumber: "6482100888",
      },
      collections: { flawless: false, blockchain: true, trulyBrilliant: true },
      price: 14200,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.princess, "2.04 ct Princess Diamond"),
      ],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "lab",
      shape: "cushion",
      carat: 1.21,
      cut: "Good",
      color: "H",
      clarity: "SI1",
      polish: "Good",
      symmetry: "Very Good",
      fluorescence: "Strong",
      lengthMm: 6.1,
      widthMm: 5.85,
      depthMm: 4.0,
      tablePercent: 61,
      depthPercent: 66,
      lengthWidthRatio: 1.043,
      certification: {
        lab: "IGI",
        reportNumber: "IGI-1122334455",
      },
      collections: { flawless: false, blockchain: false, trulyBrilliant: false },
      price: 2100,
      images: [demoImage(DEMO_DIAMOND_IMAGES.cushion, "1.21 ct Cushion Diamond")],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "natural",
      shape: "pear",
      carat: 1.18,
      cut: "Ideal",
      color: "F",
      clarity: "VS1",
      polish: "Excellent",
      symmetry: "Excellent",
      fluorescence: "None",
      lengthMm: 8.45,
      widthMm: 5.52,
      depthMm: 3.4,
      tablePercent: 57,
      depthPercent: 61.5,
      lengthWidthRatio: 1.53,
      certification: {
        lab: "GIA",
        reportNumber: "6482100777",
      },
      collections: { flawless: false, blockchain: true, trulyBrilliant: true },
      price: 6100,
      images: [demoImage(DEMO_DIAMOND_IMAGES.pear, "1.18 ct Pear Diamond")],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "lab",
      shape: "marquise",
      carat: 1.35,
      cut: "Super Ideal",
      color: "E",
      clarity: "VVS2",
      polish: "Excellent",
      symmetry: "Excellent",
      fluorescence: "Faint",
      lengthMm: 10.2,
      widthMm: 5.1,
      depthMm: 3.2,
      tablePercent: 56,
      depthPercent: 62.8,
      lengthWidthRatio: 2.0,
      certification: {
        lab: "IGI",
        reportNumber: "IGI-5566778899",
      },
      collections: { flawless: false, blockchain: false, trulyBrilliant: true },
      price: 4200,
      salePrice: 3890,
      images: [
        demoImage(DEMO_DIAMOND_IMAGES.marquise, "1.35 ct Marquise Diamond"),
      ],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "natural",
      shape: "round",
      carat: 0.78,
      cut: "Excellent",
      color: "H",
      clarity: "VS1",
      polish: "Excellent",
      symmetry: "Excellent",
      fluorescence: "None",
      lengthMm: 5.9,
      widthMm: 5.93,
      depthMm: 3.6,
      tablePercent: 56,
      depthPercent: 60.8,
      lengthWidthRatio: 0.995,
      certification: {
        lab: "GIA",
        reportNumber: "1234567891",
      },
      collections: { flawless: false, blockchain: false, trulyBrilliant: false },
      price: 2450,
      images: [
        demoImage(
          DEMO_DIAMOND_IMAGES.roundBrilliant,
          "0.78 ct Round Brilliant Diamond",
        ),
      ],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "lab",
      shape: "radiant",
      carat: 1.4,
      cut: "Ideal",
      color: "F",
      clarity: "VS1",
      polish: "Excellent",
      symmetry: "Excellent",
      fluorescence: "None",
      lengthMm: 7.8,
      widthMm: 5.6,
      depthMm: 3.7,
      tablePercent: 64,
      depthPercent: 66,
      lengthWidthRatio: 1.39,
      certification: {
        lab: "IGI",
        reportNumber: "IGI-7788990011",
      },
      collections: { flawless: false, blockchain: true, trulyBrilliant: true },
      price: 4550,
      images: [demoImage(DEMO_DIAMOND_IMAGES.radiant, "1.40 ct Radiant Diamond")],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "natural",
      shape: "asscher",
      carat: 1.08,
      cut: "Very Good",
      color: "G",
      clarity: "VS2",
      polish: "Excellent",
      symmetry: "Very Good",
      fluorescence: "None",
      lengthMm: 5.85,
      widthMm: 5.82,
      depthMm: 3.9,
      tablePercent: 62,
      depthPercent: 67,
      lengthWidthRatio: 1.005,
      certification: {
        lab: "GIA",
        reportNumber: "6482100666",
      },
      collections: { flawless: false, blockchain: false, trulyBrilliant: true },
      price: 4900,
      images: [demoImage(DEMO_DIAMOND_IMAGES.asscher, "1.08 ct Asscher Diamond")],
      availabilityStatus: "in-stock",
      isActive: true,
    },
    {
      diamondType: "lab",
      shape: "heart",
      carat: 1.12,
      cut: "Ideal",
      color: "E",
      clarity: "VVS2",
      polish: "Excellent",
      symmetry: "Excellent",
      fluorescence: "Faint",
      lengthMm: 6.5,
      widthMm: 7.0,
      depthMm: 3.9,
      tablePercent: 56,
      depthPercent: 58,
      lengthWidthRatio: 0.93,
      certification: {
        lab: "IGI",
        reportNumber: "IGI-3344556677",
      },
      collections: { flawless: false, blockchain: false, trulyBrilliant: true },
      price: 3980,
      images: [demoImage(DEMO_DIAMOND_IMAGES.heart, "1.12 ct Heart Diamond")],
      availabilityStatus: "in-stock",
      isActive: true,
    },
  ]);

  console.log("Creating ring settings...");
  await RingSetting.insertMany([
    {
      name: "Classic Solitaire Setting",
      slug: "classic-solitaire-setting",
      style: "solitaire",
      basePrice: 820,
      description:
        "A timeless four-prong solitaire — clean lines, maximum light, quiet presence.",
      images: [
        demoImage(DEMO_SETTING_IMAGES.classicSolitaire, "Classic Solitaire Setting"),
      ],
      availableMetals: ["white-gold", "yellow-gold", "rose-gold", "platinum"],
      compatibleDiamondShapes: ["round", "oval", "cushion"],
      minRingSize: "3",
      maxRingSize: "11",
      productionTime: "2–3 weeks",
      status: "published",
      isFeatured: true,
    },
    {
      name: "Hidden Halo Setting",
      slug: "hidden-halo-setting",
      style: "halo",
      basePrice: 1180,
      description:
        "A concealed halo beneath the centre stone — brilliance without visual noise.",
      images: [
        demoImage(DEMO_SETTING_IMAGES.hiddenHalo, "Hidden Halo Setting"),
      ],
      availableMetals: ["white-gold", "rose-gold", "platinum"],
      compatibleDiamondShapes: ["round", "oval"],
      minRingSize: "4",
      maxRingSize: "10",
      productionTime: "3–4 weeks",
      status: "published",
      isFeatured: true,
    },
    {
      name: "Cathedral Setting",
      slug: "cathedral-setting",
      style: "solitaire",
      basePrice: 980,
      description:
        "Graceful cathedral shoulders that elevate the centre diamond with architectural poise.",
      images: [demoImage(DEMO_SETTING_IMAGES.cathedral, "Cathedral Setting")],
      availableMetals: ["white-gold", "platinum"],
      compatibleDiamondShapes: ["emerald", "oval", "asscher"],
      minRingSize: "3",
      maxRingSize: "11",
      productionTime: "2–3 weeks",
      status: "published",
      isFeatured: false,
    },
    {
      name: "Signature Prong Setting",
      slug: "signature-prong-setting",
      style: "solitaire",
      basePrice: 1050,
      description:
        "A refined prong setting with slender lines — the diamond remains the focus.",
      images: [
        demoImage(DEMO_SETTING_IMAGES.signatureProng, "Signature Prong Setting"),
      ],
      availableMetals: ["white-gold", "platinum"],
      compatibleDiamondShapes: ["round", "oval", "cushion", "pear"],
      minRingSize: "3",
      maxRingSize: "11",
      productionTime: "2–3 weeks",
      status: "published",
      isFeatured: false,
    },
    {
      name: "Asscher Three-Stone Setting",
      slug: "asscher-three-stone-setting",
      style: "three-stone",
      basePrice: 1480,
      description:
        "An Asscher centre with tapered baguette side stones — geometric, balanced, and quietly grand.",
      images: [
        demoImage(
          DEMO_RING_IMAGES.asscherThreeStone,
          "Asscher Three-Stone Setting",
        ),
      ],
      availableMetals: ["white-gold", "platinum"],
      compatibleDiamondShapes: ["asscher", "emerald", "cushion"],
      minRingSize: "4",
      maxRingSize: "10",
      productionTime: "3–4 weeks",
      status: "published",
      isFeatured: true,
    },
    {
      name: "Emerald Baguette Three-Stone Setting",
      slug: "emerald-baguette-three-stone-setting",
      style: "three-stone",
      basePrice: 1520,
      description:
        "A step-cut emerald centre flanked by baguettes — Art Deco calm with modern polish.",
      images: [
        demoImage(
          DEMO_RING_IMAGES.emeraldCut,
          "Emerald Baguette Three-Stone Setting",
        ),
      ],
      availableMetals: ["white-gold", "platinum", "yellow-gold"],
      compatibleDiamondShapes: ["emerald", "asscher", "oval"],
      minRingSize: "3",
      maxRingSize: "11",
      productionTime: "3–4 weeks",
      status: "published",
      isFeatured: true,
    },
    {
      name: "Vintage Pear Filigree Setting",
      slug: "vintage-pear-filigree-setting",
      style: "vintage",
      basePrice: 1360,
      description:
        "Milgrain and openwork shoulders cradle a pear centre — romantic heritage, modern light.",
      images: [
        demoImage(DEMO_RING_IMAGES.pearFiligree, "Vintage Pear Filigree Setting"),
      ],
      availableMetals: ["yellow-gold", "rose-gold"],
      compatibleDiamondShapes: ["pear", "oval", "marquise"],
      minRingSize: "4",
      maxRingSize: "10",
      productionTime: "4–5 weeks",
      status: "published",
      isFeatured: false,
    },
    {
      name: "Princess Channel Setting",
      slug: "princess-channel-setting",
      style: "channel",
      basePrice: 1420,
      description:
        "A square princess centre with continuous channel-set companions — architectural sparkle.",
      images: [
        demoImage(
          DEMO_RING_IMAGES.princessChannel,
          "Princess Channel Setting",
        ),
      ],
      availableMetals: ["white-gold", "platinum"],
      compatibleDiamondShapes: ["princess", "radiant", "cushion"],
      minRingSize: "4",
      maxRingSize: "10",
      productionTime: "3–4 weeks",
      status: "published",
      isFeatured: false,
    },
    {
      name: "Marquise Bezel Setting",
      slug: "marquise-bezel-setting",
      style: "bezel",
      basePrice: 1280,
      description:
        "An east-west marquise in a dual-tone bezel — modern, secure, and sculptural.",
      images: [
        demoImage(DEMO_RING_IMAGES.marquiseBezel, "Marquise Bezel Setting"),
      ],
      availableMetals: ["white-gold", "yellow-gold", "platinum"],
      compatibleDiamondShapes: ["marquise", "oval", "pear"],
      minRingSize: "3",
      maxRingSize: "11",
      productionTime: "3–4 weeks",
      status: "published",
      isFeatured: false,
    },
    {
      name: "Cushion Pavé Split Setting",
      slug: "cushion-pave-split-setting",
      style: "pave",
      basePrice: 1580,
      description:
        "A cushion centre with a pavé split shank — soft brilliance and a warm two-tone glow.",
      images: [
        demoImage(
          DEMO_RING_IMAGES.cushionSplitShank,
          "Cushion Pavé Split Setting",
        ),
      ],
      availableMetals: ["yellow-gold", "rose-gold", "white-gold"],
      compatibleDiamondShapes: ["cushion", "round", "oval"],
      minRingSize: "4",
      maxRingSize: "10",
      productionTime: "3–4 weeks",
      status: "published",
      isFeatured: true,
    },
    {
      name: "Round Halo Pavé Setting",
      slug: "round-halo-pave-setting",
      style: "halo",
      basePrice: 1640,
      description:
        "A round brilliant framed by a full halo and pavé band — classic radiance, quietly elevated.",
      images: [
        demoImage(DEMO_RING_IMAGES.roundHalo, "Round Halo Pavé Setting"),
      ],
      availableMetals: ["white-gold", "platinum", "rose-gold"],
      compatibleDiamondShapes: ["round", "oval", "cushion"],
      minRingSize: "4",
      maxRingSize: "10",
      productionTime: "3–4 weeks",
      status: "published",
      isFeatured: true,
    },
  ]);

  console.log("Creating sample order...");
  await Order.create({
    orderNumber: generateOrderNumber(),
    customer: {
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "+1 555-0100",
    },
    items: [
      {
        itemType: "product",
        quantity: 1,
        unitPrice: 1299,
        totalPrice: 1299,
        snapshot: {
          name: "Oval Solitaire Diamond Ring",
          price: 1299,
          images: [
            demoImage(DEMO_RING_IMAGES.ovalSolitaire, "Oval Solitaire Diamond Ring"),
          ],
          selectedOptions: {
            metal: "platinum",
            ringSize: "6",
          },
        },
      },
    ],
    subtotal: 1299,
    discountTotal: 0,
    shippingTotal: 0,
    taxTotal: 104,
    total: 1403,
    currency: "USD",
    status: "paid",
    paymentStatus: "paid",
    shippingAddress: {
      line1: "123 Main Street",
      city: "New York",
      state: "NY",
      postalCode: "10001",
      country: "US",
    },
  });

  console.log("Creating sample appointment...");
  await Appointment.create({
    name: "John Doe",
    email: "john@example.com",
    phone: "+1 555-0200",
    appointmentType: "diamond-consultation",
    preferredDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    preferredTime: "14:00",
    budget: "$5,000 - $10,000",
    message:
      "Looking for a round brilliant around 1 carat with GIA report, and guidance on a solitaire setting.",
    status: "requested",
  });

  console.log("\nSeed completed successfully!");
  console.log("\nDemo images: place JPGs under public/images/demo/ (see README.md)");
  console.log("\nAdmin credentials:");
  console.log("  Email: admin@didi.com");
  console.log("  Password: admin123");

  process.exit(0);
}

seed().catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
